### PR TITLE
Adds reading comprehension dependency

### PR DESCRIPTION
**Pull request by dirkgr**
This will probably not work yet.

### CODE REVIEW

**Comment by dirkgr** [comment]
This won't work until https://github.com/allenai/allennlp-reading-comprehension/pull/15 is merged.

**Comment by dirkgr** [comment]
The sketchy thing is that the results of all the semparse tests changed when I updated the semparse version. Those results look reasonable, not random, but I'm not into those tasks enough to know whether they are expected changes.

**Comment by dirkgr** [comment]
Apparently there are different results again when this runs in TC.

**Comment by brendan-ai2** [comment]
Yeah, the diff looks pretty minor. IIRC we've seen this before when some dependency (Spacy?) updates. Maybe add a no-op diff to each requirements.txt file in order to break the Docker caching? I suspect your change will pass then (assuming you have the newest version of the dependency) and we can go ahead with the change. If it doesn't pass, the outdated deps may be on your end.

**Review by brendan-ai2 — APPROVED** [review]
Either way, LGTM when the tests pass. Thanks for this fix!

**Pull request merged**
